apiVersion: apps/v1 
kind: Deployment
metadata:
  name: doom
  namespace: kubedoom
spec:
  selector:
    matchLabels:
      app: doom
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1      
  replicas: 1 
  template:
    metadata:
      labels:
        app: doom
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
      - name: kubedoom
        image: storaxdev/kubedoom:0.5.0
        ports:
        - containerPort: 5900
          protocol: TCP
